server:
  port: 8081
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka8080.com:8080/eureka,http://eureka8081.com:8081/eureka,http://eureka8082.com:8082/eureka
  instance:
    hostname: eureka8081.com